services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: what_to_eat
    ports:
      - "5432:5432"

  migrate:
    build: .
    volumes:
      - .:/what_to_eat
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/what_to_eat
    depends_on:
      - db
    command: >
      ./scripts/wait-for-db.sh db
      alembic upgrade head

  api:
    build: .
    volumes:
      - .:/what_to_eat
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/what_to_eat
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: >
      ./scripts/wait-for-db.sh db
      uvicorn app.main:app --host 0.0.0.0 --port 8000